import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { motion } from "framer-motion";
const formatPrice = (v) => v.toLocaleString("en-US", { style: "currency", currency: "USD" });
export const CarCard = ({ car, onClick }) => {
    return (_jsxs(motion.div, { whileHover: { y: -4 }, className: "bg-white rounded-xl overflow-hidden shadow-soft border border-gray-100 flex flex-col cursor-pointer", onClick: onClick, children: [_jsxs("div", { className: "relative h-40 w-full", children: [_jsx("img", { src: car.image, alt: `${car.brand} ${car.model}`, className: "w-full h-full object-cover" }), _jsx("div", { className: "absolute inset-0 bg-gradient-to-t from-black/50 to-transparent" }), _jsxs("div", { className: "absolute top-2 left-2 flex flex-wrap gap-2", children: [car.badges?.map((b) => (_jsx("span", { className: "px-2 py-0.5 text-xs font-medium rounded-md bg-emerald-600 text-white shadow-sm", children: b }, b))), car.featured && (_jsx("span", { className: "px-2 py-0.5 text-xs font-medium rounded-md bg-brand-600 text-white shadow-sm", children: "Destaque" })), car.promoted && (_jsx("span", { className: "px-2 py-0.5 text-xs font-medium rounded-md bg-pink-600 text-white shadow-sm", children: "Premium" }))] })] }), _jsxs("div", { className: "p-4 flex flex-col flex-1", children: [_jsxs("div", { className: "flex items-start justify-between mb-2", children: [_jsxs("h3", { className: "font-semibold text-gray-900 leading-tight", children: [car.brand, " ", car.model, " ", _jsxs("span", { className: "text-gray-400 font-normal", children: ["\u2014 ", car.year] })] }), _jsx("span", { className: "text-sm font-semibold text-gray-900", children: formatPrice(car.price) })] }), _jsxs("div", { className: "grid grid-cols-3 gap-2 text-[11px] text-gray-600 mb-3", children: [_jsxs("div", { className: "flex items-center gap-1", children: [_jsx("span", { className: "inline-block w-1.5 h-1.5 rounded-full bg-brand-500" }), " ", car.mileage, " km"] }), _jsxs("div", { className: "flex items-center gap-1", children: [_jsx("span", { className: "inline-block w-1.5 h-1.5 rounded-full bg-brand-500" }), " ", car.fuel] }), _jsxs("div", { className: "flex items-center gap-1", children: [_jsx("span", { className: "inline-block w-1.5 h-1.5 rounded-full bg-brand-500" }), " ", car.transmission] })] }), _jsx("p", { className: "text-xs text-gray-500 line-clamp-2 mb-4", children: car.description }), _jsxs("div", { className: "mt-auto flex items-center justify-between", children: [_jsxs("button", { className: "text-sm font-medium text-brand-600 hover:text-brand-700 inline-flex items-center gap-1", onClick: (e) => {
                                    e.stopPropagation();
                                    onClick();
                                }, children: ["Ver Detalhes", _jsx("svg", { className: "w-4 h-4", fill: "none", stroke: "currentColor", viewBox: "0 0 24 24", children: _jsx("path", { strokeLinecap: "round", strokeLinejoin: "round", strokeWidth: 2, d: "M9 5l7 7-7 7" }) })] }), _jsx("span", { className: "text-[11px] uppercase tracking-wide font-medium text-gray-400", children: car.condition === "novo" ? "Novo" : "Usado" })] })] })] }));
};
